version: "3.8"

services:
  mqtt-client:
    build: .
    container_name: mqtt-backend
    depends_on:
      - mqtt-broker
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    ports:
      - "1884:1884"  # če boš rabil WebSocket port (ni nujno)
    networks:
      - mqtt-net

  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"  # WebSocket port, če uporabljaš transport="websockets"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - mqtt-net

networks:
  mqtt-net:
    driver: bridge
