name: Auto Server Deployment

on:
  push:
    branches:
      - no

jobs:

  server-upload:
    name: Server Upload
    runs-on: self-hosted
    steps:
    - name: Get project from Github
      uses: actions/checkout@v4
    
    - name: Upload files
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.SERVER_URL }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        uploads: |
          ./ => ./deployment/
        ignore: |
            NPO/app/**
            NPO/app/
            RAIN/web-scrapper/**
            RAIN/web-scrapper/

  server-setup:
    name: Server Setup
    runs-on: self-hosted
    needs: server-upload
    steps:

      - name: Unzip negatives
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            unzip -o ./deployment/ORV/app/data/negatives.zip -d ./deployment/ORV/app/data
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

      - name: Clean and setup containers
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ./deployment/
            bash server-clean.sh
            bash server-setup.sh
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}

  test-containers:
    name: Test Server Containers
    runs-on: self-hosted
    needs: server-setup
    
    steps:
      - name: Get project from Github
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install libraries
        run: |
          cd .tests
          pip install -r requirements.txt
      
      - name: Run MongoDB test
        run: python3 .tests/test_mongo.py

      - name: Run Node test
        run: python3 .tests/test_node.py

      - name: Run MQTT test
        run: python3 .tests/test_mqtt.py