name: Deploy to DockerHub

on:
  push:
    branches:
      - main

jobs:
  vsebnik:
    runs-on: self-hosted
    steps:

      - name: Get project from Github
        uses: actions/checkout@v4
      
      - name: Build and push to DockerHub 
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          registry: docker.io
          dockerfile: ./RAIN/mqtt-backend/Dockerfile
          tags: mqtt-backend
          image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}